### ISSUE TITLE
Special Infected is not showing

### ISSUE THREAD

**Issue by Rambizzingo** [gh-0x/l4d2-internal-base#3]
![image](https://github.com/user-attachments/assets/7b33e6fb-8a3d-4335-a404-6f19458c8975)

Hello, this is the code you made but i changed it a little bit. The problem in here is only the bots showing when you turn on the Special Infected ESP, like PlayerFreeTest is not showing but BOT: Hunter is showing. I mean only if a bot is Special Infected we can only see him.

![resim_2024-12-03_165903469](https://github.com/user-attachments/assets/7bd5f549-b116-4980-9d27-351f1b6b465c)

But! If we do this, every person in the server will be in the esp. So how can we make a esp for **Special Infected Real Players**, thanks for sharing the source code.

**Comment by xastrix** [comment]
😯

**Comment by Rambizzingo** [comment]
Is there a way to make it or not?

**Comment by xastrix** [comment]
> Is there a way to make it or not?

I have no way to check your code, but I can already see the error
![image](https://github.com/user-attachments/assets/32d44467-1406-4f6d-b703-be642a9541a6)

maybe you wanted to change the code to:
```c
if (m_classes->class_id == ET_SurvivorDeathModel || m_classes->class_id == ET_SurvivorRescue)
```

**Comment by xastrix** [comment]
Anyway, the project has an [WTFPL](https://github.com/gh-0x/l4d2-internal-base/blob/master/LICENSE) license, you can do whatever you want with the code

**Comment by Rambizzingo** [comment]
> > Is there a way to make it or not?
> 
> I have no way to check your code and make "Special Infected Real Players", but I can already see the error
> 
> ![image](https://private-user-images.githubusercontent.com/45708305/392321311-32d44467-1406-4f6d-b703-be642a9541a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzcyMDgsIm5iZiI6MTczMzMzNjkwOCwicGF0aCI6Ii80NTcwODMwNS8zOTIzMjEzMTEtMzJkNDQ0NjctMTQwNi00ZjZkLWI3MDMtYmU2NDJhOTU0MWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE4MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjg5MGYzYmUzNmI3MzAzMmY1ZjdmNzA1MTNiMGM5Yzg0YjMyNjA0YWE2YmNhZTY0NmZlNDg0MGFkZDY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hBFVfW8zNZSYrRtaE42yCpWfuCoIipLtgU2mmexw-kE)
> 
> maybe you wanted to change the code to:
> 
> ```c
> if (m_classes->class_id == ET_SurvivorDeathModel || m_classes->class_id == ET_SurvivorRescue)
> ```

I mean that i can see the **Special Infected** *Bots* not the **Special Infected** *Players*, but thank you for fixing my error.

**Comment by Rambizzingo** [comment]
> > Is there a way to make it or not?
> 
> I have no way to check your code and make "Special Infected Real Players", but I can already see the error
> 
> ![image](https://private-user-images.githubusercontent.com/45708305/392321311-32d44467-1406-4f6d-b703-be642a9541a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzcyMDgsIm5iZiI6MTczMzMzNjkwOCwicGF0aCI6Ii80NTcwODMwNS8zOTIzMjEzMTEtMzJkNDQ0NjctMTQwNi00ZjZkLWI3MDMtYmU2NDJhOTU0MWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE4MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjg5MGYzYmUzNmI3MzAzMmY1ZjdmNzA1MTNiMGM5Yzg0YjMyNjA0YWE2YmNhZTY0NmZlNDg0MGFkZDY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hBFVfW8zNZSYrRtaE42yCpWfuCoIipLtgU2mmexw-kE)
> 
> maybe you wanted to change the code to:
> 
> ```c
> if (m_classes->class_id == ET_SurvivorDeathModel || m_classes->class_id == ET_SurvivorRescue)
> ```

Accidentally closed it mb. I mean that i can see the **Special Infected** *Bots*, not the **Special Infected** *Players* how can i render **Special Infected** *Players*? (btw thank you for fixing my error on the code)
